# Site settings
title: Madhukar's Blog
email: madhukaraphatak@gmail.com
description: "Thoughts of geekperson"
baseurl: "/"
url: "http://blog.zinnianewsite.in"
username : phatak-dev
twitter : madhukaraphatak
paginate: 10


# Build settings
markdown: kramdown
permalink: /:title
