# Site settings
title: Madhukar's Blog
email: madhukaraphatak@gmail.com
description: "Thoughts on technology, life and everything else."
baseurl: ""
url: "http://blog.madhukaraphatak.com"
username : phatak-dev
twitter : madhukaraphatak
paginate: 10
exclude : [code]

# Build settings
markdown: kramdown
permalink: /:title
